set_temperature:
  name: "Set Temperature of Clage Heater"
  description: Sets the temperature of the warm water, that is leaving the heater, e.g. to the showers
  fields:
    homeserver_name:
      name: "Homeserver name"
      description: "The name you gave the homeserver during setup (slugified) or the Homeserver ID (e.g. 'F8F005DB0CD7')"
      required: true
      example: "F8F005DB0CD7"
      selector:
        text:
    heater_id:
      name: "Heater ID"
      description: "The device ID of the heater (e.g. '2049DB0CD7')"
      required: true
      example: "2049DB0CD7"
      selector:
        text:
    temperature:
      name: "Temperature"
      description: "Target temperature in °C (10-60)"
      required: true
      example: 45
      selector:
        number:
          min: 10
          max: 60
          step: 1
          unit_of_measurement: "°C"

